In [14]:
import numpy as np

In [15]:
A = np.matrix([[-2,1,3], [0,2,5]])
B = np.matrix([[3,0,2], [1,3,-1]])
C = np.matrix([[2,4], [5,4]])

In [16]:
A+B

matrix([[1, 1, 5],
        [1, 5, 4]])

In [17]:
A-B

matrix([[-5,  1,  1],
        [-1, -1,  6]])

In [19]:
2*A-3*B

matrix([[-13,   2,   0],
        [ -3,  -5,  13]])

In [18]:
A.transpose()

matrix([[-2,  0],
        [ 1,  2],
        [ 3,  5]])

In [20]:
A.transpose() * C

matrix([[-4, -8],
        [12, 12],
        [31, 32]])

In [21]:
C*C

matrix([[24, 24],
        [30, 36]])