In [1]:
import numpy as np

In [2]:
A = np.array([[1,1,5],[-3,0,1],[0,1,2],[2,-4,1]])
B = np.array([[4,0,1],[1,-4,2],[2,-1,0],[0,2,1]])
C = np.array([[2,4,0],[-1,1,1],[3,2,-1],[1,0,1]])

In [3]:
A+2*B-C

array([[ 7, -3,  7],
       [ 0, -9,  4],
       [ 1, -3,  3],
       [ 1,  0,  2]])

In [4]:
np.dot(np.matrix.transpose(A),B)

array([[ 1, 16, -3],
       [ 6, -9, -3],
       [25, -4,  8]])

In [5]:
np.dot(np.dot(A, np.matrix.transpose(B)), C)

array([[ 21,  45,  13],
       [-38, -57,   6],
       [  5,   6,   5],
       [ 15,  72,   5]])