In [1]:
import numpy as np

In [2]:
x = np.array([-3,4,1,5,2])
y = np.array([2,0,4,-3,-1])
z = np.array([7,-1,0,2,3])
A = np.array([[5,1,-4,-2,1], [0,2,4,-3,-1]])

In [3]:
x + y

array([-1,  4,  5,  2,  1])

In [4]:
y-z

array([-5,  1,  4, -5, -4])

In [5]:
4*x

array([-12,  16,   4,  20,   8])

In [6]:
x+3*y-2*z

array([-11,   6,  13,  -8,  -7])

In [7]:
A.dot(x)

array([-23,  -5])